### ISSUE TITLE
which function you used to run Clojure code

### ISSUE THREAD

**Issue by kangaroolab** [jurjanpaul/ape-cljs-playground#6]
looking at your source code, I couldn't tell...is it load-string? please clarify. thanks.

**Comment by jurjanpaul** [comment]
Yes, it's using Scittle's `load-string` (from function `load-code`). Does that help?

**Comment by kangaroolab** [comment]
thanks...I don't see load-string from scittle. I only see eval_string and eval_string_tag. can you help further clarify?

**Comment by jurjanpaul** [comment]
It's been a while since I did this, but a quick Google search turned up my interaction with Scittle's author on Clojurians' slack two years ago: https://clojurians-log.clojureverse.org/scittle/2022-08-12
(He fixed that particular issue soon after.)
How I read it, it seems `eval-string` would indeed work just as well. `load-string` is just the clojure.core name which Scittle  also implements and exposes (through some Sci configuration if I remember correctly). If you want to further understand Scittle I suggest you dive into that source code and/or ask your question in the #scittle channel on Clojurians Slack (as I did).

**Comment by jurjanpaul** [comment]
Now that I'm actually looking at Scittle's source code again, I also wonder how I ever found that I could just use `load-string`. I'm sorry, but I really don't remember and neither whether I saw some advantage compared to `eval-string` (though I would think so).

**Comment by jurjanpaul** [comment]
Ok, I think I found it: `load-string` is simply exposed by sci by default from its `sci.impl.namespaces` namespace.

**Comment by kangaroolab** [comment]
Thanks...actually I am a big fan of scittle and here is a note editor I put together with scittle embedded (you can add code editor when adding a note). https://kangaroolab.github.io/tippy/

I looked at your code and tried to learn how to redirect print output, which is something l am thinking to enable...essentially I think your code for it is (print-to-output (eval_string code)) which capture all the println and last return of the code execution, correct?

**Comment by jurjanpaul** [comment]
Relevant code:
```

(def output (r/atom nil))
(defn print-to-output [s]
  (swap! output str s "\n"))

;; Originally went with just `binding` `*print-fn*` and `*print-err-fn*`, but
;; that failed to be sufficient for functions invoked (again) from Reagent.
(alter-var-root (var *print-fn*)
                (constantly print-to-output))
(alter-var-root (var *print-err-fn*)
                (constantly print-to-output))
```

and in `load-code` the return value is indeed also fed to `print-to-output` as you can see.
